### ISSUE TITLE
On windows box, simply yields the error "cannot find the path specified."

### ISSUE THREAD

**Issue by UInIQ** [bibixx/drumroll#14]
![image](https://user-images.githubusercontent.com/17788145/54386373-c8bdc800-4666-11e9-954c-5b4091a35d17.png)

Doesn't matter if it's run (or installed) from Git Bash either:
![image](https://user-images.githubusercontent.com/17788145/54386302-a2982800-4666-11e9-931c-d4d7624e531c.png)

I'm assuming this is a PATH variable issue, but I cannot for the life of me figure out what it's LOOKING for.

**Comment by bibixx** [comment]
Hey @UInIQ,
Sorry for late response but somehow I didn't get any notification. I'll look into is as soon as I get access to the windows machine.

**Comment by bibixx** [comment]
It should be fixed now. Surprisingly this issue had nothing to do with missing files nor paths. It simply didn't support Windows.
And the message that appeared was created while checking for dependencies and while doing it it should have redirected output to `/dev/null`. On Windows however you have to redirect it to `NUL`. Please check if it works for you and if yes close this issue 🙏

**Comment by UInIQ** [comment]
Right on! I’ll check as soon as I get into the office. Drumroll please…

**Comment by bibixx** [comment]
🥁

**Comment by bibixx** [comment]
@UInIQ kind remider 😉
